arb-dir: lib/presentation/common/localizations
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: lib/presentation/common/localizations/untranslated_localizations.txt